### ISSUE TITLE
thank!

### ISSUE THREAD

**Issue by lasthrun** [JoshyFrancis/DragX#1]
your java script is work great! it is the only one frame work i found that can have a good support on mobile and desktop, and can be scroll able.
but i need more document to use it. the source is hard to read, i think we should make it reformat with a better code style.

**Comment by JoshyFrancis** [comment]
I have little time to write documentation. These all I have coded in spare time. Please collaborate with me in this project. Sorry for being late to write a reply. I was very busy with some urgent works in my company.

**Comment by JoshyFrancis** [comment]
I know there are some discrepancies here and there in the functionalities. Please report it.

**Comment by lasthrun** [comment]
i am try to reformat your code. but i fail... it is too hard to read.

**Comment by JoshyFrancis** [comment]
I am very sorry that I cannot help you now, because I am very busy with my work now. I do reformat it when i get spare time. Please forgive me.
